# Must be unique in a given SonarQube instance
sonar.projectName=ofm
sonar.projectKey=bcgov_ECC-OFM
sonar.organization=bcgov-sonarcloud

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**, **/coverage/**, **/tests/**/*.js
#sonar.verbose=true

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=./backend/src, ./frontend/src
sonar.coverage.exclusions=**/*.*
