---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: '${REPO_NAME}-template'
metadata:
  name: '${REPO_NAME}-frontend-deployment'
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        app: '${APP_NAME}-frontend-${ENVIRONMENT}'
        branch: '${BRANCH}'
      name: '${APP_NAME}-frontend-${ENVIRONMENT}'
    spec:
      replicas: ${{MIN_REPLICAS}}
      selector:
        matchLabels:
          app: '${APP_NAME}-frontend-${ENVIRONMENT}'
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
          maxSurge: 25%
      template:
        metadata:
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
          labels:
            app: '${APP_NAME}-frontend-${ENVIRONMENT}'
        spec:
          containers:
            - image: image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/${REPO_NAME}-frontend:${TAG}
              imagePullPolicy: Always
              volumeMounts:
                - name: js-runtime-config
                  mountPath: '/srv/js/config'
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: '/'
                  port: 2015
                  scheme: HTTP
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              name: '${APP_NAME}-frontend-${ENVIRONMENT}'
              ports:
                - containerPort: 2015
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: '/'
                  port: 2015
                  scheme: HTTP
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources:
                requests:
                  cpu: '${MIN_CPU}'
                  memory: '${MIN_MEM}'
                limits:
                  cpu: '${MAX_CPU}'
                  memory: '${MAX_MEM}'
          volumes:
            - name: js-runtime-config
              configMap:
                name: ofm-frontend-${ENVIRONMENT}-config-map
      test: false
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        service.alpha.openshift.io/serving-cert-secret-name: 'ofm-frontend-cert'
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        app: '${APP_NAME}-frontend-${ENVIRONMENT}'
      name: '${APP_NAME}-frontend-${ENVIRONMENT}'
    spec:
      ports:
        - name: 2015-tcp
          port: 2015
          protocol: TCP
          targetPort: 2015
      selector:
        app: '${APP_NAME}-frontend-${ENVIRONMENT}'
  - apiVersion: v1
    kind: Route
    metadata:
      name: '${APP_NAME}-frontend-${ENVIRONMENT}'
      labels:
        app: '${APP_NAME}-frontend-${ENVIRONMENT}'
      annotations:
        openshift.io/host.generated: 'true'
        router.openshift.io/cookie-same-site: 'Strict'
    spec:
      to:
        kind: Service
        name: '${APP_NAME}-frontend-${ENVIRONMENT}'
        weight: 100
      port:
        targetPort: 2015-tcp
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None
  - apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: '${APP_NAME}-frontend-${ENVIRONMENT}-cpu-autoscaler'
    spec:
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: '${APP_NAME}-frontend-${ENVIRONMENT}'
        subresource: scale
      minReplicas: ${{MIN_REPLICAS}}
      maxReplicas: ${{MAX_REPLICAS}}
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 90
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ofm-frontend-${ENVIRONMENT}-config-map
      namespace: '${NAMESPACE}'
    data:
      config.js: |
        const config = {
          BANNER_ENVIRONMENT: '${BANNER_ENVIRONMENT}',
          BANNER_COLOR: '${BANNER_COLOR}',
          TDAD_CONTACT_EMAIL: '${TDAD_CONTACT_EMAIL}',
          IRREGULAR_EXPENSE_FORM_URL: '${IRREGULAR_EXPENSE_FORM_URL}'
        };
parameters:
  - name: REPO_NAME
    description: Application repository name
    required: true
  - name: BRANCH
    description: Job identifier (i.e. 'pr-5' OR 'master')
    required: true
  - name: NAMESPACE
    description: Target namespace reference (i.e. 'k8vopl-dev')
    required: true
  - name: ENVIRONMENT
    description: The environment being created ('dev', 'test', 'uat', 'prod')
    required: true
  - name: APP_NAME
    description: Application name
    required: true
  - name: HOST_ROUTE
    description: The host the route will use to expose service outside cluster
    required: false
  - name: TAG
    description: The identifying tag for this specific deployment
    required: true
  - name: MIN_REPLICAS
    description: The minimum amount of replicas
    required: true
  - name: MAX_REPLICAS
    description: The maximum amount of replicas
    required: true
  - name: MIN_CPU
    description: The minimum amount of cpu
    required: true
  - name: MAX_CPU
    description: The maximum amount of cpu
    required: true
  - name: MIN_MEM
    description: The minimum amount of memory
    required: true
  - name: MAX_MEM
    description: The maximum amount of memory
    required: true
  - name: CA_CERT
    description: The CA Certificate
    required: false
  - name: CERTIFICATE
    description: The Certificate
    required: false
  - name: PRIVATE_KEY
    description: The private key
    required: false
  - name: BANNER_ENVIRONMENT
    description: The title for the application banner. It which indicates what environment is running
    required: false
  - name: BANNER_COLOR
    description: The CSS color for the BANNER_ENVIRONMENT background
    required: false
  - name: TDAD_CONTACT_EMAIL
    description: The contact email for 10 dollar a day daycare centers
    required: false
  - name: IRREGULAR_EXPENSE_FORM_URL
    description: The URL to download the Irregular Expense application form.
    required: false
