# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Backend

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - 'feature/**'
      - 'Feature/**'
      - 'fix/*'
      - 'Fix/*'
      - 'ofmcc-*'
    paths:
      - 'backend/src/**'
  pull_request:
    branches: [main]
    paths:
      - 'backend/src/**'

jobs:
  test:
    name: Run ESLint
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.16.x'
      - run: npm ci
      - run: npm run lint
        env:
          NODE_ENV: 'test'

  # TODO: Uncomment after project is set up in sonar
  # sonarcloud:
  #   name: Build (Sonar Cloud)
  #   runs-on: ubuntu-24.04
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         # Disabling shallow clone is recommended for improving relevancy of reporting
  #         fetch-depth: 0
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '14.x'
  #     - name: SonarCloud Scan
  #       uses: sonarsource/sonarcloud-github-action@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #with:
  #args: >
  #-Dsonar.exclusions=**/test/**,.github/**/*,*.md
  #-Dsonar.organization=bcgov-sonarcloud
  #-Dsonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
  #-Dsonar.project.monorepo.enabled=true
  #-Dsonar.projectKey=${{ github.event.repository.name }}
  #-Dsonar.sources=backend
  #-Dsonar.tests=backend/tests
