name: Release Tag

env:
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: ${{ secrets.OFM_NAMESPACE_NO_ENV }}-dev

  REPO_NAME: 'ecc-ofm'
  BRANCH: ${{ github.ref_name }}
  APP_NAME_FRONTEND: 'frontend'
  APP_NAME_BACKEND: 'backend'

on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows
  workflow_dispatch:
    inputs:
      rc_version:
        description: 'Release Candidate Version'
        required: true
      release_version:
        description: 'Final Release Version'
        required: true

jobs:
  openshift-ci-cd:
    name: Tag Image
    # ubuntu-20.04 can also be used.
    runs-on: ubuntu-24.04
    environment: dev
    steps:
      - name: Print Workflow Dispatch Inputs and Env Vars
        uses: shayki5/print-workflow-dispatch-inputs@v1
        with:
          add_to_summary: 'true'
          print_env_vars: 'false'
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get tag
        id: get-tag
        uses: actions/github-script@v6
        with:
          script: |
            return github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'tags/${{ github.event.inputs.rc_version }}',
            })
      - name: Echo tag
        run: |
          echo "getRef sha ${{ steps.get-tag.outputs.result.data.object.sha }}"

#      - name: Create tag
#        uses: actions/github-script@v6
#        with:
#          script: |
#            github.rest.git.getRef({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              ref: 'refs/tags/${{ github.event.inputs.release_version }}',
#              sha: ${{ steps.get-tag.outputs.result.data.object.sha }}
#            })

#      - name: Install oc
#        uses: redhat-actions/openshift-tools-installer@v1
#        with:
#          oc: 4.16
#
#      - uses: actions/checkout@v3
#      - name: Tag in OpenShift
#        run: |
#          set -eux
#          # Login to OpenShift and select project
#          oc login --token=${{ env.OPENSHIFT_TOKEN }} --server=${{ env.OPENSHIFT_SERVER }}
#          oc project ${{ env.OPENSHIFT_NAMESPACE }}
#
#          oc tag ${{ env.OPENSHIFT_NAMESPACE }}/${{ env.REPO_NAME }}-${{ env.APP_NAME_FRONTEND }}:latest ${{ env.OPENSHIFT_NAMESPACE }}/${{ env.REPO_NAME }}-${{ env.APP_NAME_FRONTEND }}:${{ github.event.inputs.release_version }}
#          oc tag ${{ env.OPENSHIFT_NAMESPACE }}/${{ env.REPO_NAME }}-${{ env.APP_NAME_BACKEND }}:latest ${{ env.OPENSHIFT_NAMESPACE }}/${{ env.REPO_NAME }}-${{ env.APP_NAME_BACKEND }}:${{ github.event.inputs.release_version }}
